Pin docker api version
I'm unsure exactly why this started happening because it doesn't seem to
have started after a change to a version of a docker dependency. The
error we were getting when doing a docker build inside the build image
was this:

ERROR: failed to build: Error response from daemon: client version 1.52 is too new. Maximum supported API version is 1.43: driver not connecting

For more info see this PR:
https://github.com/wildfly/wildfly-operator/pull/338